version: "3.8"

services:
  # Database of the application (Postgres)
  app-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SampleDriverDb
      TZ: Europe/Warsaw
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p "${POSTGRES_PORT}"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - appnet
  # Backend of the application (ASP.NET Core)
  app-api:
    build:
      context: ./SampleAspNetReactDockerApp.Server
      dockerfile: Dockerfile
    ports:
      - "${ASPNETCORE_APP_PORT}:${ASPNETCORE_APP_PORT}"
    environment:
        ASPNETCORE_ENVIRONMENT: "PRODUCTION"
        ASPNETCORE_APP_DB: "${ASPNETCORE_APP_DB}"
        ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION: "${ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION}"
        ASPNETCORE_APP_PORT: "${ASPNETCORE_APP_PORT}"
        CLIENT_APP_PORTS: "${CLIENT_APP_PORTS}"
        POSTGRES_PORT: "${POSTGRES_PORT}"
    depends_on:
      - app-db
    networks:
      - appnet
  # Frontend of the application (React-Vite)
  app-client:
    build:
      context: ./SampleAspNetReactDockerApp.Client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_APP_PORTS}"
    environment:
      ASPNETCORE_ENVIRONMENT: "PRODUCTION"
      ASPNETCORE_APP_DB: "${ASPNETCORE_APP_DB}"
      ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION: "${ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION}"
      ASPNETCORE_APP_PORT: "${ASPNETCORE_APP_PORT}"
      CLIENT_APP_PORTS: "${CLIENT_APP_PORTS}"
    depends_on:
      - app-api
    networks:
      - appnet
volumes:
  app_data:

networks:
  appnet:
    driver: bridge